version: '3'

services:
  web:
    container_name: "react-universal-web"
    build:
      context: ./
      dockerfile: /docker/Dockerfile-prod
    volumes:
      - ./build:/var/www/react-universal:rw
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/default-ssl:/etc/nginx/sites-available/default-ssl:ro
      - ./conf/server.crt:/etc/nginx/ssl/server.crt:ro
      - ./conf/server.key:/etc/nginx/ssl/server.key:ro
    ports:
      - "8090:8090"
      - "443:443"
    links:
      - mongodb
    depends_on:
      - mongodb

  dev:
    container_name: "react-universal-dev"
    build:
      context: ./
      dockerfile: /docker/Dockerfile-dev
    volumes:
      - ./:/react-universal:rw
    ports:
      - "4000:4000"

  wss:
    container_name: "react-universal-wss"
    build:
      context: ./
      dockerfile: /docker/Dockerfile-wss
    volumes:
      - ./:/react-universal:rw
    ports:
      - "3000:3000"

  mongodb:
      image: mongo:latest
      container_name: "react-universal-mongodb"
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
      volumes:
        - ./data/db:/data/db
      ports:
          - 27017:27017
      command: mongod --smallfiles --logpath=/dev/null # --quiet
