version: '3'

# Data volume for Mongo
volumes:
  mongostorage:

services:

  #
  # Web container
  #
  web:
    container_name: "react-universal-web"
    build:
      context: ./
      dockerfile: /docker/Dockerfile-prod
    volumes:
      - ./build:/var/www/react-universal:rw
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/default-ssl:/etc/nginx/sites-available/default-ssl:ro
      - ./conf/server.crt:/etc/nginx/ssl/server.crt:ro
      - ./conf/server.key:/etc/nginx/ssl/server.key:ro
    ports:
      - "8090:8090"
      - "443:443"
    links:
      - mongodb
      - restapi
    depends_on:
      - mongodb
      - restapi

  #
  # Development server with HMR
  #
  dev:
    container_name: "react-universal-dev"
    build:
      context: ./
      dockerfile: /docker/Dockerfile-dev
    volumes:
      - ./:/react-universal:rw
    ports:
      - "4000:4000"

  #
  # WebSocket server
  #
  wss:
    container_name: "react-universal-wss"
    build:
      context: ./
      dockerfile: /docker/Dockerfile-wss
    volumes:
      - ./:/react-universal:rw
    ports:
      - "3100:3100"

  #
  # Mongo Database
  #
  mongodb:
    image: mongo:latest
    container_name: "react-universal-mongodb"
    # https://hub.docker.com/r/alexpunct/mongo/
    image: alexpunct/mongo:3.4
    # We use mongostorage data volume and we will use the /data/db path for the database inside the container
    volumes:
      - mongostorage:/data/db
    # Expose a MongoDB port to connect to, defined by the MONGODB_EXPOSED_PORT environment variable
    # and map this port to the 27017 internal port which is what MongoDB uses
    ports:
      - "${MONGODB_EXPOSED_PORT}:27017"
    # Passing environment variables from the host to the container.
    # Our container expects the following variables (as explained here: https://hub.docker.com/r/alexpunct/mongo/)
    environment:
      MONGODB_ADMIN_USER: $MONGODB_ADMIN_USER
      MONGODB_ADMIN_PASS: $MONGODB_ADMIN_PASS
      MONGODB_APPLICATION_DATABASE: $MONGODB_APPLICATION_DATABASE
      MONGODB_APPLICATION_USER: $MONGODB_APPLICATION_USER
      MONGODB_APPLICATION_PASS: $MONGODB_APPLICATION_PASS

  #
  # REST API service
  #
  restapi:
    # Give it a name
    container_name: restapi_container
    # https://hub.docker.com/r/linuxenko/mongo-rest/
    image: linuxenko/mongo-rest
    # The port that our API will have exposed so we can connect to
    ports:
      - "${REST_API_EXPOSED_PORT}:3000"
    # This field creates a hosts file entry in our container that points to the mongodb service
    # so we can access it with the hostname mongo as in http://mongo:3000 from this container.
    # It also tells the mongodb service to allow our service to connect to it (if we hand't have exposed a port already)
    # Ultimately, it makes sure that mongodb starts before our restaapi service
    links:
      - mongodb:mongo
    # Environment variables passed to the container.
    environment:
      ME_CONFIG_APIKEY: $REST_API_APIKEY
      ME_CONFIG_DBSTRING: "mongodb://${MONGODB_APPLICATION_USER}:${MONGODB_APPLICATION_PASS}@mongo:27017/${MONGODB_APPLICATION_DATABASE}"
