FROM kyma/docker-nginx

COPY conf/nginx.conf /etc/nginx/nginx.conf
COPY conf/default-ssl /etc/nginx/sites-available/default-ssl
COPY build/ /var/www/react-universal/build
ADD conf/server.crt /etc/nginx/ssl/
ADD conf/server.key /etc/nginx/ssl/
EXPOSE 8090

CMD 'nginx'
