version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: /docker/Dockerfile-prod
    volumes:
      - ./build:/var/www/react-universal:rw
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/default-ssl:/etc/nginx/sites-available/default-ssl:ro
      - ./conf/server.crt:/etc/nginx/ssl/server.crt:ro
      - ./conf/server.key:/etc/nginx/ssl/server.key:ro
    ports:
      - "8090:8090"
      - "443:443"
  dev:
    build:
      context: ./
      dockerfile: /docker/Dockerfile-dev
    volumes:
      - ./:/react-universal:rw
    ports:
      - "4000:4000"
